### PR TITLE
Attach generated zip to GitHub Releases using GitHub Actions

### PR DESCRIPTION
**Pull request by JohnPeel**
This is a github action configuration using the [BigWigs packager](https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow).

It creates an addon zip by reading the .pkgmeta file, and uploads it to GitHub Releases as an asset.

This properly solves #5 and #10.

If you provide your CurseForge api key as a secret to the action (CF_API_KEY), it will even automate releases on CurseForge when you tag them.

### CODE REVIEW

**Comment by JohnPeel** [comment]
If you provide you CurseForge api key as a secret to the action (CF_API_KEY), it will even automate releases on CurseForge when you tag them.

**Comment by GurliGebis** [comment]
There is already automatic publishing to curseforge when I push a tag, so I cannot see the idea of using a github action to do the same?

**Comment by JohnPeel** [comment]
Some people would like to not have to rely on curseforge.

Primarily this uploads a proper zip to Releases, so that other addon managers can just pull from GitHub, rather than curseforge.

**Comment by GurliGebis** [comment]
Let's see if it works.

**Comment by GurliGebis** [comment]
@JohnPeel I just pushed v0.34.0, and it looks like it has been built and uploaded correctly :)

**Pull request merged**
